version: 2
jobs:
 prebuild:
   machine: true
   steps:
   - run: |
       wget https://releases.hashicorp.com/terraform/0.10.8/terraform_0.10.8_linux_amd64.zip 
       unzip terraform_0.10.8_linux_amd64.zip
       ls -la terraform
   - save_cache:
       key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
       paths:
         - ./terraform
 build:
   machine: true
   steps:
     - checkout
     - run: docker build -t sails-app:$CIRCLE_BRANCH .
 postbuild:
    machine: true
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run : |
          ls - la
          ./terraform 
      
workflows:
  version: 2
  build_and_test:
    jobs:
      - prebuild
      - postbuild:
          requires:
            - prebuild
