version: 2
jobs:
 getTerraform:
   machine: true
   steps:
   - run: |
       wget https://releases.hashicorp.com/terraform/0.10.8/terraform_0.10.8_linux_amd64.zip 
       unzip terraform_0.10.8_linux_amd64.zip
       ls -la terraform
   - save_cache:
       key: tf-{{ .Environment.CIRCLE_SHA1 }}
       paths:
         - ./terraform
 getDeploymentIaC:
  machine: true
  steps:
  - run: |
      git clone git@github.com:Amal-V/terraform-example.git 
  - save_cache:
      key: iac-{{ .Environment.CIRCLE_SHA1 }}
      paths:
        - ./terraform-example
 build:
   machine: true
   steps:
     - checkout
     - run: docker build -t sails-app:$CIRCLE_BRANCH .
 deployment:
   machine: true
   steps:
     - restore_cache:
         key: tf-{{ .Environment.CIRCLE_SHA1 }}
     - restore_cache:
         key: iac-{{ .Environment.CIRCLE_SHA1 }}
     - working_directory ./terraform-example/
     - run: terraform plan
      
workflows:
  version: 2
  build_and_test:
    jobs:
      - getTerraform
      - getDeploymentIaC
      - deployment:
          requires:
            - getTerraform
            - getDeploymentIaC
      
